### ISSUE TITLE
Home corrections

### ISSUE THREAD

**Issue by hernaneg350** [pata-pila/web#60]
(ignore header corrections)

<img width="763" alt="Screen Shot 2020-08-31 at 16 37 37" src="https://user-images.githubusercontent.com/3202866/91759586-48678b80-eba8-11ea-94bb-c394555dfb21.png">

<img width="776" alt="Screen Shot 2020-08-31 at 16 37 45" src="https://user-images.githubusercontent.com/3202866/91759601-4dc4d600-eba8-11ea-82fb-32f0f39d1e6c.png">

**Comment by tfoxy** [comment]
Solved in #61
